name: xdev-bot
channels:
  - conda-forge
dependencies:
  - codecov
  - pandas
  - pytest-cov
  - pytest==4.2.0
  - python=3.6
  - s3fs
  - bidict
  - pip:
      - aiohttp==3.5.4
      - cachetools==3.1.0
      - gidgethub==3.1.0
      - pytest-aiohttp==0.3.0
      - pytest-asyncio==0.10.0
