name: xdev-bot
channels:
  - conda-forge
dependencies:
  - python=3.7
  - codecov
  - pytest==4.2.0
  - pytest-cov
  - pip:
      - gidgethub==3.1.0
      - aiohttp==3.5.4
      - cachetools==3.1.0
      - pytest-asyncio==0.10.0
      - pytest-aiohttp==0.3.0


    